#!/usr/bin/env python3

import os
from os import path


def main():
    project_dir = path.dirname(path.dirname(path.abspath(__file__)))
    labs_dir = path.join(project_dir, 'labs')

    for dir_path, _, file_names in os.walk(solutions_dir):
        for file_name in file_names:
            source = path.join(dir_path, file_name)
            target = path.join(labs_dir, path.relpath(source, solutions_dir))
            link_path = path.relpath(source, path.dirname(target))

            while True:
                try:
                    os.symlink(link_path, target)
                except FileExistsError:
                    os.remove(target)
                else:
                    break


if __name__ == '__main__':
    main()
