#!/usr/bin/env python3

import os
from os import path
import subprocess


_TESTS = [
    (
        'util',
        [
            'sleep',
            'pingpong',
            'primes',
            'find',
            'xargs',
        ],
    ),
    (
        'syscall',
        [
            'trace',
            'sysinfo',
        ]
    ),
]


def main():
    os.chdir(path.dirname(path.dirname(path.abspath(__file__))))

    for (i, (lab, problems)) in enumerate(_TESTS, 1):
        for problem in problems:
            subprocess.run([f'./grade-lab-{lab}', problem], cwd=path.join('labs', f'{i:02}-{lab}'), check=True)


if __name__ == '__main__':
    main()
